# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\pythonProject\guiDvora.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from CLIENT import client
from PyQt5 import QtCore, QtGui, QtWidgets
import json

class Ui_MainWindow(object):

    def __init__(self, ip, address):
        self.centralwidget = None
        self.exit_btn = None
        self.reset_btn = None
        self.inputFrame = None
        self.usrId_label = None
        self.status_label = None
        self.wallet_label = None
        self.wallet_input = None
        self.comboBox = None
        self.cardId_label = None
        self.contract_label = None
        self.userId_input = None
        self.cardId_input = None
        self.frame = None
        self.createCard_btn = None
        self.changeContract_btn = None
        self.fillWallet_btn = None
        self.payRide_btn = None
        self.getDataCard_btn = None
        self.menubar = None
        self.statusbar = None
        self.label = None
        self.label_1 = None
        self.label_2 = None
        self.label_3 = None
        self.label_4 = None
        self.label_5 = None
        self.label_6 = None
        self.label_7 = None
        self.label_8 = None
        self.label_9 = None
        self.client = client.Client(ip, address)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setObjectName("exit_btn")
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setGeometry(QtCore.QRect(113, 10, 93, 28))
        self.reset_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_btn.setObjectName("reset_btn")
        self.inputFrame = QtWidgets.QFrame(self.centralwidget)
        self.inputFrame.setGeometry(QtCore.QRect(50, 70, 491, 461))
        self.inputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputFrame.setObjectName("inputFrame")
        self.usrId_label = QtWidgets.QLabel(self.inputFrame)
        self.usrId_label.setGeometry(QtCore.QRect(160, 30, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usrId_label.setFont(font)
        self.usrId_label.setObjectName("usrId_label")
        self.label = QtWidgets.QLabel(self.inputFrame)
        self.label.setGeometry(QtCore.QRect(160, 67, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.inputFrame)
        self.label_2.setGeometry(QtCore.QRect(160, 102, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.wallet_input = QtWidgets.QSpinBox(self.inputFrame)
        self.wallet_input.setGeometry(QtCore.QRect(260, 103, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wallet_input.setFont(font)
        self.wallet_input.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.wallet_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.wallet_input.setMaximum(9999)
        self.wallet_input.setSingleStep(10)
        self.wallet_input.setObjectName("wallet_input")
        self.comboBox = QtWidgets.QComboBox(self.inputFrame)
        self.comboBox.setGeometry(QtCore.QRect(260, 140, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.inputFrame)
        self.label_3.setGeometry(QtCore.QRect(160, 130, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.userId_input = QtWidgets.QLineEdit(self.inputFrame)
        self.userId_input.setGeometry(QtCore.QRect(260, 31, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userId_input.setFont(font)
        self.userId_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.userId_input.setPlaceholderText("")
        self.userId_input.setObjectName("userId_input")
        self.cardId_input = QtWidgets.QLineEdit(self.inputFrame)
        self.cardId_input.setGeometry(QtCore.QRect(260, 67, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cardId_input.setFont(font)
        self.cardId_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.cardId_input.setObjectName("cardId_input")
        self.status_label = QtWidgets.QLabel(self.inputFrame)
        self.status_label.setGeometry(QtCore.QRect(60, 310, 381, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.status_label.setFont(font)
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.label_4 = QtWidgets.QLabel(self.inputFrame)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 481, 291))
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_4.setPixmap(
            QtGui.QPixmap("./rav-kav.png"))
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.usrId_label.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.wallet_input.raise_()
        self.comboBox.raise_()
        self.label_3.raise_()
        self.userId_input.raise_()
        self.cardId_input.raise_()
        self.status_label.raise_()
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(580, 10, 381, 521))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.createCard_btn = QtWidgets.QPushButton(self.frame)
        self.createCard_btn.setGeometry(QtCore.QRect(40, 20, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.createCard_btn.setFont(font)
        self.createCard_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createCard_btn.setAutoFillBackground(False)
        self.createCard_btn.setObjectName("createCard_btn")
        self.changeContract_btn = QtWidgets.QPushButton(self.frame)
        self.changeContract_btn.setGeometry(QtCore.QRect(40, 420, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.changeContract_btn.setFont(font)
        self.changeContract_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changeContract_btn.setObjectName("changeContract_btn")
        self.fillWallet_btn = QtWidgets.QPushButton(self.frame)
        self.fillWallet_btn.setGeometry(QtCore.QRect(40, 320, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fillWallet_btn.setFont(font)
        self.fillWallet_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fillWallet_btn.setObjectName("fillWallet_btn")
        self.payRide_btn = QtWidgets.QPushButton(self.frame)
        self.payRide_btn.setGeometry(QtCore.QRect(40, 220, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.payRide_btn.setFont(font)
        self.payRide_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.payRide_btn.setObjectName("payRide_btn")
        self.getDataCard_btn = QtWidgets.QPushButton(self.frame)
        self.getDataCard_btn.setGeometry(QtCore.QRect(40, 120, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.getDataCard_btn.setFont(font)
        self.getDataCard_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.getDataCard_btn.setObjectName("getDataCard_btn")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(60, 90, 251, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(60, 190, 251, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(60, 290, 251, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(60, 390, 251, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(60, 490, 251, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.createCard_btn.setStyleSheet("background-color: rgb(116, 147, 141, 1)")
        self.getDataCard_btn.setStyleSheet("background-color: rgb(143, 176, 170, 1)")
        self.payRide_btn.setStyleSheet("background-color: rgb(116, 147, 141, 1)")
        self.fillWallet_btn.setStyleSheet("background-color: rgb(143, 176, 170, 1)")
        self.changeContract_btn.setStyleSheet("background-color: rgb(116, 147, 141, 1)")
        self.exit_btn.setStyleSheet("background-color: rgb(142, 147, 142, 1)")
        self.reset_btn.setStyleSheet("background-color: rgb(142, 147, 142, 1)")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))
        self.reset_btn.setText(_translate("MainWindow", "Reset screen"))
        self.usrId_label.setText(_translate("MainWindow", "User Id:"))
        self.label.setText(_translate("MainWindow", "Card No. "))
        self.label_2.setText(_translate("MainWindow", "Wallet:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "NONE"))
        self.comboBox.setItemText(1, _translate("MainWindow", "NORTH"))
        self.comboBox.setItemText(2, _translate("MainWindow", "CENTER"))
        self.comboBox.setItemText(3, _translate("MainWindow", "SOUTH"))
        self.label_3.setText(_translate("MainWindow", "Contract:"))
        self.createCard_btn.setText(_translate("MainWindow", "Create Card"))
        self.changeContract_btn.setText(_translate("MainWindow", "Change Contract"))
        self.fillWallet_btn.setText(_translate("MainWindow", "Fill Wallet"))
        self.payRide_btn.setText(_translate("MainWindow", "Pay for Ride"))
        self.getDataCard_btn.setText(_translate("MainWindow", "Scan Card"))
        self.label_5.setText(_translate("MainWindow", "Requierd: User id   Op.: Wallet, Contract"))
        self.label_6.setText(_translate("MainWindow", "Requierd: Card No."))
        self.label_7.setText(_translate("MainWindow", "Requierd: Card No. , Contract"))
        self.label_8.setText(_translate("MainWindow", "Requierd: Card No. , Wallet"))
        self.label_9.setText(_translate("MainWindow", "Requierd: Card No. , Contract"))

        self.createCard_btn.clicked.connect(lambda: self.run('1'))
        self.getDataCard_btn.clicked.connect(lambda: self.run('2'))
        self.payRide_btn.clicked.connect(lambda: self.run('3'))
        self.fillWallet_btn.clicked.connect(lambda: self.run('4'))
        self.changeContract_btn.clicked.connect(lambda: self.run('5'))
        self.exit_btn.clicked.connect(self.exit)
        self.reset_btn.clicked.connect(self.reset)

    def exit(self):
        self.client.close_connection()
        QtWidgets.QApplication.quit()

    def reset(self):
        self.status_label.setText("")
        self.cardId_input.setText("")
        self.userId_input.setText("")
        self.wallet_input.setValue(0)
        self.comboBox.setCurrentText("NONE")

    def run(self, requset):
        self.status_label.setText("")
        # create card
        if requset == '1':
            ans = self.client.connect(requset, json.dumps({'user_id': self.userId_input.text(), 'contract_name': str(self.comboBox.currentText()), 'wallet': self.wallet_input.value()}))
            if ans["status"] == "Done":
                self.cardId_input.setText(str(ans["params"]["card_id"]))
                self.status_label.setText("Completed successfully")

        # get card data
        elif requset == '2':
            ans = self.client.connect(requset, json.dumps({'card_id': self.cardId_input.text()}))
            if ans["status"] == "Done":
                self.cardId_input.setText(str(ans["params"]['card_id']))
                self.comboBox.setCurrentText(ans["params"]["contract_name"])
                self.wallet_input.setValue(int(ans["params"]["wallet"]))
                self.status_label.setText("Completed successfully")

        # pay for ride / change contract
        elif requset == '3' or requset == '5':
            ans = self.client.connect(requset, json.dumps({'card_id': self.cardId_input.text(), 'contract_name': str(self.comboBox.currentText())}))
            if ans["status"] == "Done":
                self.status_label.setText("Completed successfully")
                self.run('2')

        # fill wallet
        elif requset == '4':
            ans = self.client.connect(requset, json.dumps({'card_id': self.cardId_input.text(), 'sum': self.wallet_input.value()}))
            if ans["status"] == "Done":
                self.status_label.setText("Completed successfully")
                self.run('2')

        # if operation status = Failed
        if ans["status"] == "connectionFails":
            self.status_label.setText("The operation failed, \nplease check the connection.")
        elif ans["status"] == "Fails":
            self.status_label.setText("The operation failed, \nplease check the data you entered.")
